### ISSUE TITLE
'redux-actions' module not included by default, but referenced in Tutorial code

### ISSUE THREAD

**Issue by oppodeldoc** [heygrady/react-redux-notes#1]
Following this tutorial to the letter throws an error on webpack builds when getting down to the Todos.js module because the default starter kit doesn't have redux-actions, or at least, it wasn't present in my installation. Maybe need to add it manually (and in the docs) with `npm install --save redux-actions`?

**Comment by heygrady** [comment]
Yep. you need to install it. Good catch.
